### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by SeKi81** [sonyxperiadev/device-sony-kitakami#101]
hardware/qcom/display/msm8994/liboverlay/overlayUtils.cpp: In function 'int overlay::utils::getMdpFormat(int, int)':
hardware/qcom/display/msm8994/liboverlay/overlayUtils.cpp:153:24: error: 'MDP_RGBA_8888_UBWC' was not declared in this scope
                 return MDP_RGBA_8888_UBWC;
                        ^
hardware/qcom/display/msm8994/liboverlay/overlayUtils.cpp:155:24: error: 'MDP_RGB_565_UBWC' was not declared in this scope
                 return MDP_RGB_565_UBWC;
                        ^
hardware/qcom/display/msm8994/liboverlay/overlayUtils.cpp:159:24: error: 'MDP_Y_CBCR_H2V2_UBWC' was not declared in this scope
                 return MDP_Y_CBCR_H2V2_UBWC;
                        ^
build/core/binary.mk:706: die Regel für Ziel „out/target/product/sumire/obj_arm/SHARED_LIBRARIES/liboverlay_intermediates/overlayUtils.o“ scheiterte
make: **\* [out/target/product/sumire/obj_arm/SHARED_LIBRARIES/liboverlay_intermediates/overlayUtils.o] Fehler 1
make: **\* Es wird auf noch nicht beendete Prozesse gewartet...

**Comment by zwliew** [comment]
Kernel headers need to be updated for this.

**Comment by jerpelea** [comment]
please follow compilation guide 
headers are updated !

**Comment by SeKi81** [comment]
i did followed the guide. The kernel is wrong in the guide!
guide said: git checkout aosp/AU_LINUX_ANDROID_LA.BF64.1.1_RB1.05.00.02.172.061

and the working one is AU_LINUX_ANDROID_LA.BF64.1.2.1_RB1.05.00.02.019.067

**Comment by jerpelea** [comment]
We all use aosp/AU_LINUX_ANDROID_LA.BF64.1.1_RB1.05.00.02.172.061

Please follow the guide

**Comment by SeKi81** [comment]
I am following the guide and it does not work with the above issue!
So pls fix source or the guide - i did twice now.

redownloaded the whole aosp source and added all the stuff from the guide.

**Comment by jerpelea** [comment]
are you using inline kernel building or using prebuilt kernel ?

**Comment by SeKi81** [comment]
its the prebuilt one.. thats why im so confused.

**Comment by jerpelea** [comment]
no problem 
i will start a clean build to test

**Comment by SeKi81** [comment]
Thank you!
